version: "3"

services:
  mongodb:
    container_name: mongo_db
    image: mongo:5.0.15
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mongo_database
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db
    command: mongod --auth